# code: language=ansible
---
- name: Deinstall crc
  hosts: localhost
  gather_facts: false
  vars_files: vars.yaml
  vars_prompt:
    - name: sudo_pass
      prompt: "Provide your sudo password to start the deinstallation"

  tasks:
    - name: Remove user from kubeconfig
      ansible.builtin.shell: oc logout | true

    - name: Remove CRC instance
      loop:
        - crc stop
        - crc delete --clear-cache
        - crc cleanup
      ansible.builtin.command: sg libvirt -c "{{ item }}"

    - name: Remove CRC files
      become: true
      loop:
        - /tmp/crc-linux-{{ crc_version }}-amd64/crc
        - /usr/local/bin/crc
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"

    - name: Remove oc
      become: true
      ansible.builtin.file:
        state: absent
        path: /usr/local/bin/oc

    - name: Remove user from 'libvirt' group
      become: true
      ansible.builtin.command: "gpasswd --delete {{ ansible_user }} libvirt"
