---
- name: Deinstall crc
  hosts: localhost
  connection: local
  vars_files: vars.yaml
  tasks:
    - name: Remove user from kubeconfig
      tags: skip_ansible_lint
      ansible.builtin.shell: oc logout | true

    - name: Remove crc instance
      loop:
        - crc stop
        - crc delete --clear-cache --force
        - crc cleanup
      ansible.builtin.command: sg libvirt -c "{{ item }}"

    - name: Remove files
      become: true
      loop:
        - /tmp/crc-linux-{{ crc_version }}-amd64/
        - /usr/local/bin/crc
        - /usr/local/bin/oc
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"

    - name: Remove user from 'libvirt' group
      become: true
      ansible.builtin.command: "gpasswd --delete {{ ansible_env.USER }} libvirt"
