---
- name: Deinstall CRC
  hosts: localhost
  connection: local
  vars_files: vars.yaml
  tasks:
    - name: Remove user from kubeconfig
      tags: skip_ansible_lint
      ansible.builtin.shell: oc logout | true

    - name: Remove CRC instance
      loop:
        - crc stop
        - crc delete --clear-cache
        - crc cleanup
      ansible.builtin.command: sg libvirt -c "{{ item }}"

    - name: Remove CRC files
      become: true
      loop:
        - /tmp/crc-linux-{{ crc_version }}-amd64/
        - /usr/local/bin/crc
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"

    - name: Remove oc
      become: true
      ansible.builtin.file:
        state: absent
        path: /usr/local/bin/oc

    - name: Remove user from 'libvirt' group
      become: true
      ansible.builtin.command: "gpasswd --delete {{ ansible_env.USER }} libvirt"
