---
- name: Remove CRC and the required packages, caches and components
  hosts: localhost
  vars_prompt:
    - name: sudo_pass
      prompt: "Provide your sudo password to start the deinstallation "

  vars_files: vars.yaml

  tasks:
    - name: Remove user from kubeconfig
      ansible.builtin.shell: oc logout | true

    - name: Remove oc binary
      become: true
      ansible.builtin.file:
        state: absent
        path: /usr/local/bin/oc

    - name: Remove CRC instance
      ansible.builtin.command: sg libvirt -c "{{ item }}"
      loop:
        - crc stop
        - crc delete --clear-cache
        - crc cleanup

    - name: Remove CRC dir and binary
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - /usr/local/bin/crc-linux-{{ crc_version }}-amd64/crc
        - /usr/local/bin/crc

    - name: Remove current user from group 'libvirt'
      become: true
      ansible.builtin.command: gpasswd --delete {{ lookup('env', 'USER') }} libvirt
