---
- name: Install crc {{ crc_version }}
  hosts: localhost
  connection: local
  vars_files: vars.yaml
  pre_tasks:
    - name: Check pull-secret.json
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/pull-secret.json"
      register: pullsecret_json

    - name: Fail if it doesn't exist
      when: not pullsecret_json.stat.exists
      ansible.builtin.fail:
        msg: >-
          The mandatory 'pull-secret.json' file doesn't exist.
          Read the "Requirements" section in README.md on how to create it.

    - name: Fail if crc_version is not valid
      when: crc_version is not regex("([\d.]+)")
      ansible.builtin.fail:
        msg: >-
          The specified crc_version is not valid.
          Checkout the "Update" section in README.md on which versions are supported.

  tasks:
    - name: Install required packages
      become: true
      tags: prerequisites
      ansible.builtin.package:
        name:
          - qemu-kvm
          - libvirt-daemon
          - libvirt-daemon-system
          - network-manager

    - name: Download crc {{ crc_version }}
      tags: download
      become: true
      ansible.builtin.unarchive:
        src: "https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/{{ crc_version }}/crc-linux-amd64.tar.xz"
        remote_src: true
        dest: /tmp
        mode: "0755"
        owner: "{{ ansible_env.USER }}"
        group: root
        creates: "/tmp/crc-linux-{{ crc_version }}-amd64"
      register: crc_download
      until: crc_download is succeeded
      retries: 5
      delay: 3

    - name: Make crc executable
      tags: download
      become: true
      ansible.builtin.copy:
        src: "/tmp/crc-linux-{{ crc_version }}-amd64/crc"
        remote_src: true
        dest: /usr/local/bin/crc
        mode: "0755"
        owner: "{{ ansible_env.USER }}"
        group: root

    - name: Add user to 'libvirt' group
      tags: download
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        append: true
        groups:
          - libvirt

    - name: Enable cluster monitoring
      when: crc_cluster_monitoring
      tags: setup
      loop:
        - crc config set cpus 6
        - crc config set memory 14336
        - crc config set enable-cluster-monitoring true
      ansible.builtin.command: sg libvirt -c "{{ item }}"

    - name: Print time info
      tags: setup
      ansible.builtin.debug:
        msg: "Entered 'Setup and start crc' at {{ ansible_date_time.iso8601 }} UTC."

    - name: Setup and start crc (this can take up to 1h)
      tags: setup
      loop:
        - crc setup
        - crc config set kubeadmin-password kubeadmin
        - crc config set pull-secret-file {{ playbook_dir }}/pull-secret.json
        - crc start
      ansible.builtin.command: sg libvirt -c "{{ item }}"

    - name: Setup oc
      tags: setup
      become: true
      ansible.builtin.copy:
        src: "{{ ansible_env.HOME }}/.crc/bin/oc/oc"
        remote_src: true
        dest: /usr/local/bin/oc
        owner: "{{ ansible_env.USER }}"
        group: root
        mode: "0755"
        force: true

    - name: Run oc login
      tags: test
      ansible.builtin.command: >
        oc login -u developer -p developer https://api.crc.testing:6443 --insecure-skip-tls-verify

    - name: Run, check, delete alpine pod in developer project as test
      tags: test
      ansible.builtin.shell: |
        set -o pipefail
        oc new-project developer | true
        oc run alpine --command sleep 300 --image alpine:3.18.3
        oc wait --for=condition=Ready --timeout 15m pod/alpine
        oc delete pod/alpine --force

    - name: Print crc webconsole info
      ansible.builtin.debug:
        msg: >-
          You can now login at https://console-openshift-console.apps-crc.testing with
          developer/developer or kubeadmin/kubeadmin credentials.
