---
- name: Configure cpu usage
  ansible.builtin.shell: sg libvirt -c "crc config set cpus 6"

- name: Configure memory usage
  ansible.builtin.shell: sg libvirt -c "crc config set memory 14336"

- name: Enable cluster monitoring
  ansible.builtin.shell: sg libvirt -c "crc config set enable-cluster-monitoring true"
