---
- name: Download and install code ready containers
  hosts: localhost
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Provide your sudo password to start the play"
  roles:
    - role: download_install_crc
      tags: ["download", "install", "crc"]
